### PR TITLE
move to open weather api

### LINKED ISSUE #18: Move to OpenWeather API
We are using somewhat limited but free FCC Weather API.
It's time to upgrade to OpenWeather API and unlock more data and opportunities for next features.

[OpenWeather API](https://openweathermap.org/current) has limited number of requests and thus requires API key. You can either create your own account and generate your key or ask on our Discord for mine.
The API key needs to be send with each request. You do not want to upload this key to GitHub for everyone to see so you will need to create a special file (.env) to store it.

- Create .env file and incude the API key as environmental variable. [[Vite docs](https://vitejs.dev/guide/env-and-mode.html)]
- Modify .gitignore to exclude .env
- Modify `weatherDetails.js` to call OpenWeather API. [[API docs]](https://openweathermap.org/current)
- ~~Modify `updateWeather.js` to replace image `src` url with its respective icon. [[img url docs]](https://openweathermap.org/weather-conditions)~~

### PR DESCRIPTION
**Pull request by Bill-1991**
# Description
Changed api call to open weather

Fixes #18 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked the issue to this PR. [Instruction how to link issues to pull requests here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Dorfieeee — CHANGES_REQUESTED** [review]
When I run the code I get very high temperature numbers..

image

That need's to be fixed.

**Comment by Bill-1991** [comment]
I saw it but i thought maybe it was for later issue...i just took out 273.15 from each value,not sure if that's all that it needs

**Review by Dorfieeee — CHANGES_REQUESTED** [review]
I know reading docs can be boring but it can save you a lot of hassle.
Why changing all the code when you can add another parameter to the api call url? [docs](https://openweathermap.org/current)

**Comment by Bill-1991** [comment]
fixed it,thanks

**Review by Dorfieeee — APPROVED** [review]
Data displaying correctly, no new errors.
Merging initiated...

**Pull request merged**
